// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gps_data.proto

package com.nwnu.blockchain.protobuf;

/**
 * <pre>
 *1、import "address.proto"; //引入其他的proto文件，如果是其他文件夹的文件也不需要加路径，
 *只需要在生成代码时，选择proto文件的扫描范围时，需要将所有导入proro文件都包含在内。
 *通过--proto_path属性指定。
 *2、package com.study.blog.protobuf;  proto文件的命名空间
 *3、option java_package = "com.study.blog.protobuf";//生成代码后的命令空间
 *4、option java_outer_classname="Person"; //这个名字不能与下文的message名字冲突，
 *Person已经是一个message类型，就不能作为ClassName
 *5、option java_multiple_files = true; //如果为true，每个message和service都会被生成为一个类。
 *如果是false，则所有的message和service都将会是java_outer_classname的内部类
 *6、option java_generic_services = true; //是否生成Service,如果这个属性为false，
 *将不会生成Service的代码，即使已经在proto文件编写了service结构
 *7、option optimize_for = SPEED;//对生成的代码的一种优化，有三个值:SPEED,  CODE_SIZE, LITE_RUNTIME;
 *表示希望生成代码是偏向执行速度，还是生成的文件大小，如果在app端，代码文件的大小是很重要的。
 * </pre>
 *
 * Protobuf type {@code com.nwnu.blockchain.protobuf.gps_data}
 */
public  final class gps_data extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.nwnu.blockchain.protobuf.gps_data)
    gps_dataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use gps_data.newBuilder() to construct.
  private gps_data(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private gps_data() {
    terminalId_ = "";
    dataTime_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new gps_data();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private gps_data(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            terminalId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            dataTime_ = s;
            break;
          }
          case 33: {

            lon_ = input.readDouble();
            break;
          }
          case 41: {

            lat_ = input.readDouble();
            break;
          }
          case 53: {

            speed_ = input.readFloat();
            break;
          }
          case 56: {

            altitude_ = input.readInt32();
            break;
          }
          case 64: {

            locType_ = input.readInt32();
            break;
          }
          case 72: {

            gpsStatus_ = input.readInt32();
            break;
          }
          case 85: {

            direction_ = input.readFloat();
            break;
          }
          case 88: {

            satellite_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.nwnu.blockchain.protobuf.GpsData.internal_static_com_nwnu_blockchain_protobuf_gps_data_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.nwnu.blockchain.protobuf.GpsData.internal_static_com_nwnu_blockchain_protobuf_gps_data_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.nwnu.blockchain.protobuf.gps_data.class, com.nwnu.blockchain.protobuf.gps_data.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   */
  public long getId() {
    return id_;
  }

  public static final int TERMINALID_FIELD_NUMBER = 2;
  private volatile java.lang.Object terminalId_;
  /**
   * <code>string terminalId = 2;</code>
   */
  public java.lang.String getTerminalId() {
    java.lang.Object ref = terminalId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      terminalId_ = s;
      return s;
    }
  }
  /**
   * <code>string terminalId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTerminalIdBytes() {
    java.lang.Object ref = terminalId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      terminalId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATATIME_FIELD_NUMBER = 3;
  private volatile java.lang.Object dataTime_;
  /**
   * <code>string dataTime = 3;</code>
   */
  public java.lang.String getDataTime() {
    java.lang.Object ref = dataTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dataTime_ = s;
      return s;
    }
  }
  /**
   * <code>string dataTime = 3;</code>
   */
  public com.google.protobuf.ByteString
      getDataTimeBytes() {
    java.lang.Object ref = dataTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dataTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LON_FIELD_NUMBER = 4;
  private double lon_;
  /**
   * <code>double lon = 4;</code>
   */
  public double getLon() {
    return lon_;
  }

  public static final int LAT_FIELD_NUMBER = 5;
  private double lat_;
  /**
   * <code>double lat = 5;</code>
   */
  public double getLat() {
    return lat_;
  }

  public static final int SPEED_FIELD_NUMBER = 6;
  private float speed_;
  /**
   * <code>float speed = 6;</code>
   */
  public float getSpeed() {
    return speed_;
  }

  public static final int ALTITUDE_FIELD_NUMBER = 7;
  private int altitude_;
  /**
   * <code>int32 altitude = 7;</code>
   */
  public int getAltitude() {
    return altitude_;
  }

  public static final int LOCTYPE_FIELD_NUMBER = 8;
  private int locType_;
  /**
   * <code>int32 locType = 8;</code>
   */
  public int getLocType() {
    return locType_;
  }

  public static final int GPSSTATUS_FIELD_NUMBER = 9;
  private int gpsStatus_;
  /**
   * <code>int32 gpsStatus = 9;</code>
   */
  public int getGpsStatus() {
    return gpsStatus_;
  }

  public static final int DIRECTION_FIELD_NUMBER = 10;
  private float direction_;
  /**
   * <code>float direction = 10;</code>
   */
  public float getDirection() {
    return direction_;
  }

  public static final int SATELLITE_FIELD_NUMBER = 11;
  private int satellite_;
  /**
   * <code>int32 satellite = 11;</code>
   */
  public int getSatellite() {
    return satellite_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (!getTerminalIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, terminalId_);
    }
    if (!getDataTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, dataTime_);
    }
    if (lon_ != 0D) {
      output.writeDouble(4, lon_);
    }
    if (lat_ != 0D) {
      output.writeDouble(5, lat_);
    }
    if (speed_ != 0F) {
      output.writeFloat(6, speed_);
    }
    if (altitude_ != 0) {
      output.writeInt32(7, altitude_);
    }
    if (locType_ != 0) {
      output.writeInt32(8, locType_);
    }
    if (gpsStatus_ != 0) {
      output.writeInt32(9, gpsStatus_);
    }
    if (direction_ != 0F) {
      output.writeFloat(10, direction_);
    }
    if (satellite_ != 0) {
      output.writeInt32(11, satellite_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (!getTerminalIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, terminalId_);
    }
    if (!getDataTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, dataTime_);
    }
    if (lon_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, lon_);
    }
    if (lat_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, lat_);
    }
    if (speed_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(6, speed_);
    }
    if (altitude_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, altitude_);
    }
    if (locType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, locType_);
    }
    if (gpsStatus_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, gpsStatus_);
    }
    if (direction_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(10, direction_);
    }
    if (satellite_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, satellite_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.nwnu.blockchain.protobuf.gps_data)) {
      return super.equals(obj);
    }
    com.nwnu.blockchain.protobuf.gps_data other = (com.nwnu.blockchain.protobuf.gps_data) obj;

    if (getId()
        != other.getId()) return false;
    if (!getTerminalId()
        .equals(other.getTerminalId())) return false;
    if (!getDataTime()
        .equals(other.getDataTime())) return false;
    if (java.lang.Double.doubleToLongBits(getLon())
        != java.lang.Double.doubleToLongBits(
            other.getLon())) return false;
    if (java.lang.Double.doubleToLongBits(getLat())
        != java.lang.Double.doubleToLongBits(
            other.getLat())) return false;
    if (java.lang.Float.floatToIntBits(getSpeed())
        != java.lang.Float.floatToIntBits(
            other.getSpeed())) return false;
    if (getAltitude()
        != other.getAltitude()) return false;
    if (getLocType()
        != other.getLocType()) return false;
    if (getGpsStatus()
        != other.getGpsStatus()) return false;
    if (java.lang.Float.floatToIntBits(getDirection())
        != java.lang.Float.floatToIntBits(
            other.getDirection())) return false;
    if (getSatellite()
        != other.getSatellite()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + TERMINALID_FIELD_NUMBER;
    hash = (53 * hash) + getTerminalId().hashCode();
    hash = (37 * hash) + DATATIME_FIELD_NUMBER;
    hash = (53 * hash) + getDataTime().hashCode();
    hash = (37 * hash) + LON_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getLon()));
    hash = (37 * hash) + LAT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getLat()));
    hash = (37 * hash) + SPEED_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getSpeed());
    hash = (37 * hash) + ALTITUDE_FIELD_NUMBER;
    hash = (53 * hash) + getAltitude();
    hash = (37 * hash) + LOCTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getLocType();
    hash = (37 * hash) + GPSSTATUS_FIELD_NUMBER;
    hash = (53 * hash) + getGpsStatus();
    hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getDirection());
    hash = (37 * hash) + SATELLITE_FIELD_NUMBER;
    hash = (53 * hash) + getSatellite();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.nwnu.blockchain.protobuf.gps_data parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nwnu.blockchain.protobuf.gps_data parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nwnu.blockchain.protobuf.gps_data parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nwnu.blockchain.protobuf.gps_data parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nwnu.blockchain.protobuf.gps_data parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nwnu.blockchain.protobuf.gps_data parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nwnu.blockchain.protobuf.gps_data parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nwnu.blockchain.protobuf.gps_data parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nwnu.blockchain.protobuf.gps_data parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.nwnu.blockchain.protobuf.gps_data parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nwnu.blockchain.protobuf.gps_data parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nwnu.blockchain.protobuf.gps_data parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.nwnu.blockchain.protobuf.gps_data prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *1、import "address.proto"; //引入其他的proto文件，如果是其他文件夹的文件也不需要加路径，
   *只需要在生成代码时，选择proto文件的扫描范围时，需要将所有导入proro文件都包含在内。
   *通过--proto_path属性指定。
   *2、package com.study.blog.protobuf;  proto文件的命名空间
   *3、option java_package = "com.study.blog.protobuf";//生成代码后的命令空间
   *4、option java_outer_classname="Person"; //这个名字不能与下文的message名字冲突，
   *Person已经是一个message类型，就不能作为ClassName
   *5、option java_multiple_files = true; //如果为true，每个message和service都会被生成为一个类。
   *如果是false，则所有的message和service都将会是java_outer_classname的内部类
   *6、option java_generic_services = true; //是否生成Service,如果这个属性为false，
   *将不会生成Service的代码，即使已经在proto文件编写了service结构
   *7、option optimize_for = SPEED;//对生成的代码的一种优化，有三个值:SPEED,  CODE_SIZE, LITE_RUNTIME;
   *表示希望生成代码是偏向执行速度，还是生成的文件大小，如果在app端，代码文件的大小是很重要的。
   * </pre>
   *
   * Protobuf type {@code com.nwnu.blockchain.protobuf.gps_data}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.nwnu.blockchain.protobuf.gps_data)
      com.nwnu.blockchain.protobuf.gps_dataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nwnu.blockchain.protobuf.GpsData.internal_static_com_nwnu_blockchain_protobuf_gps_data_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nwnu.blockchain.protobuf.GpsData.internal_static_com_nwnu_blockchain_protobuf_gps_data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nwnu.blockchain.protobuf.gps_data.class, com.nwnu.blockchain.protobuf.gps_data.Builder.class);
    }

    // Construct using com.nwnu.blockchain.protobuf.gps_data.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      terminalId_ = "";

      dataTime_ = "";

      lon_ = 0D;

      lat_ = 0D;

      speed_ = 0F;

      altitude_ = 0;

      locType_ = 0;

      gpsStatus_ = 0;

      direction_ = 0F;

      satellite_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.nwnu.blockchain.protobuf.GpsData.internal_static_com_nwnu_blockchain_protobuf_gps_data_descriptor;
    }

    @java.lang.Override
    public com.nwnu.blockchain.protobuf.gps_data getDefaultInstanceForType() {
      return com.nwnu.blockchain.protobuf.gps_data.getDefaultInstance();
    }

    @java.lang.Override
    public com.nwnu.blockchain.protobuf.gps_data build() {
      com.nwnu.blockchain.protobuf.gps_data result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.nwnu.blockchain.protobuf.gps_data buildPartial() {
      com.nwnu.blockchain.protobuf.gps_data result = new com.nwnu.blockchain.protobuf.gps_data(this);
      result.id_ = id_;
      result.terminalId_ = terminalId_;
      result.dataTime_ = dataTime_;
      result.lon_ = lon_;
      result.lat_ = lat_;
      result.speed_ = speed_;
      result.altitude_ = altitude_;
      result.locType_ = locType_;
      result.gpsStatus_ = gpsStatus_;
      result.direction_ = direction_;
      result.satellite_ = satellite_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.nwnu.blockchain.protobuf.gps_data) {
        return mergeFrom((com.nwnu.blockchain.protobuf.gps_data)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.nwnu.blockchain.protobuf.gps_data other) {
      if (other == com.nwnu.blockchain.protobuf.gps_data.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getTerminalId().isEmpty()) {
        terminalId_ = other.terminalId_;
        onChanged();
      }
      if (!other.getDataTime().isEmpty()) {
        dataTime_ = other.dataTime_;
        onChanged();
      }
      if (other.getLon() != 0D) {
        setLon(other.getLon());
      }
      if (other.getLat() != 0D) {
        setLat(other.getLat());
      }
      if (other.getSpeed() != 0F) {
        setSpeed(other.getSpeed());
      }
      if (other.getAltitude() != 0) {
        setAltitude(other.getAltitude());
      }
      if (other.getLocType() != 0) {
        setLocType(other.getLocType());
      }
      if (other.getGpsStatus() != 0) {
        setGpsStatus(other.getGpsStatus());
      }
      if (other.getDirection() != 0F) {
        setDirection(other.getDirection());
      }
      if (other.getSatellite() != 0) {
        setSatellite(other.getSatellite());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.nwnu.blockchain.protobuf.gps_data parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.nwnu.blockchain.protobuf.gps_data) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object terminalId_ = "";
    /**
     * <code>string terminalId = 2;</code>
     */
    public java.lang.String getTerminalId() {
      java.lang.Object ref = terminalId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        terminalId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string terminalId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTerminalIdBytes() {
      java.lang.Object ref = terminalId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        terminalId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string terminalId = 2;</code>
     */
    public Builder setTerminalId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      terminalId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string terminalId = 2;</code>
     */
    public Builder clearTerminalId() {
      
      terminalId_ = getDefaultInstance().getTerminalId();
      onChanged();
      return this;
    }
    /**
     * <code>string terminalId = 2;</code>
     */
    public Builder setTerminalIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      terminalId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object dataTime_ = "";
    /**
     * <code>string dataTime = 3;</code>
     */
    public java.lang.String getDataTime() {
      java.lang.Object ref = dataTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dataTime = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDataTimeBytes() {
      java.lang.Object ref = dataTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dataTime = 3;</code>
     */
    public Builder setDataTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dataTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dataTime = 3;</code>
     */
    public Builder clearDataTime() {
      
      dataTime_ = getDefaultInstance().getDataTime();
      onChanged();
      return this;
    }
    /**
     * <code>string dataTime = 3;</code>
     */
    public Builder setDataTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dataTime_ = value;
      onChanged();
      return this;
    }

    private double lon_ ;
    /**
     * <code>double lon = 4;</code>
     */
    public double getLon() {
      return lon_;
    }
    /**
     * <code>double lon = 4;</code>
     */
    public Builder setLon(double value) {
      
      lon_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double lon = 4;</code>
     */
    public Builder clearLon() {
      
      lon_ = 0D;
      onChanged();
      return this;
    }

    private double lat_ ;
    /**
     * <code>double lat = 5;</code>
     */
    public double getLat() {
      return lat_;
    }
    /**
     * <code>double lat = 5;</code>
     */
    public Builder setLat(double value) {
      
      lat_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double lat = 5;</code>
     */
    public Builder clearLat() {
      
      lat_ = 0D;
      onChanged();
      return this;
    }

    private float speed_ ;
    /**
     * <code>float speed = 6;</code>
     */
    public float getSpeed() {
      return speed_;
    }
    /**
     * <code>float speed = 6;</code>
     */
    public Builder setSpeed(float value) {
      
      speed_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float speed = 6;</code>
     */
    public Builder clearSpeed() {
      
      speed_ = 0F;
      onChanged();
      return this;
    }

    private int altitude_ ;
    /**
     * <code>int32 altitude = 7;</code>
     */
    public int getAltitude() {
      return altitude_;
    }
    /**
     * <code>int32 altitude = 7;</code>
     */
    public Builder setAltitude(int value) {
      
      altitude_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 altitude = 7;</code>
     */
    public Builder clearAltitude() {
      
      altitude_ = 0;
      onChanged();
      return this;
    }

    private int locType_ ;
    /**
     * <code>int32 locType = 8;</code>
     */
    public int getLocType() {
      return locType_;
    }
    /**
     * <code>int32 locType = 8;</code>
     */
    public Builder setLocType(int value) {
      
      locType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 locType = 8;</code>
     */
    public Builder clearLocType() {
      
      locType_ = 0;
      onChanged();
      return this;
    }

    private int gpsStatus_ ;
    /**
     * <code>int32 gpsStatus = 9;</code>
     */
    public int getGpsStatus() {
      return gpsStatus_;
    }
    /**
     * <code>int32 gpsStatus = 9;</code>
     */
    public Builder setGpsStatus(int value) {
      
      gpsStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 gpsStatus = 9;</code>
     */
    public Builder clearGpsStatus() {
      
      gpsStatus_ = 0;
      onChanged();
      return this;
    }

    private float direction_ ;
    /**
     * <code>float direction = 10;</code>
     */
    public float getDirection() {
      return direction_;
    }
    /**
     * <code>float direction = 10;</code>
     */
    public Builder setDirection(float value) {
      
      direction_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float direction = 10;</code>
     */
    public Builder clearDirection() {
      
      direction_ = 0F;
      onChanged();
      return this;
    }

    private int satellite_ ;
    /**
     * <code>int32 satellite = 11;</code>
     */
    public int getSatellite() {
      return satellite_;
    }
    /**
     * <code>int32 satellite = 11;</code>
     */
    public Builder setSatellite(int value) {
      
      satellite_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 satellite = 11;</code>
     */
    public Builder clearSatellite() {
      
      satellite_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.nwnu.blockchain.protobuf.gps_data)
  }

  // @@protoc_insertion_point(class_scope:com.nwnu.blockchain.protobuf.gps_data)
  private static final com.nwnu.blockchain.protobuf.gps_data DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.nwnu.blockchain.protobuf.gps_data();
  }

  public static com.nwnu.blockchain.protobuf.gps_data getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<gps_data>
      PARSER = new com.google.protobuf.AbstractParser<gps_data>() {
    @java.lang.Override
    public gps_data parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new gps_data(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<gps_data> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<gps_data> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.nwnu.blockchain.protobuf.gps_data getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

