// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gps_data.proto

package com.nwnu.blockchain.protobuf;

public interface gps_dataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.nwnu.blockchain.protobuf.gps_data)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>string terminalId = 2;</code>
   */
  java.lang.String getTerminalId();
  /**
   * <code>string terminalId = 2;</code>
   */
  com.google.protobuf.ByteString
      getTerminalIdBytes();

  /**
   * <code>string dataTime = 3;</code>
   */
  java.lang.String getDataTime();
  /**
   * <code>string dataTime = 3;</code>
   */
  com.google.protobuf.ByteString
      getDataTimeBytes();

  /**
   * <code>double lon = 4;</code>
   */
  double getLon();

  /**
   * <code>double lat = 5;</code>
   */
  double getLat();

  /**
   * <code>float speed = 6;</code>
   */
  float getSpeed();

  /**
   * <code>int32 altitude = 7;</code>
   */
  int getAltitude();

  /**
   * <code>int32 locType = 8;</code>
   */
  int getLocType();

  /**
   * <code>int32 gpsStatus = 9;</code>
   */
  int getGpsStatus();

  /**
   * <code>float direction = 10;</code>
   */
  float getDirection();

  /**
   * <code>int32 satellite = 11;</code>
   */
  int getSatellite();
}
