// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gps_data.proto

package com.nwnu.blockchain.protobuf;

public final class GpsData {
  private GpsData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_nwnu_blockchain_protobuf_gps_data_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_nwnu_blockchain_protobuf_gps_data_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016gps_data.proto\022\034com.nwnu.blockchain.pr" +
      "otobuf\"\301\001\n\010gps_data\022\n\n\002id\030\001 \001(\003\022\022\n\ntermi" +
      "nalId\030\002 \001(\t\022\020\n\010dataTime\030\003 \001(\t\022\013\n\003lon\030\004 \001" +
      "(\001\022\013\n\003lat\030\005 \001(\001\022\r\n\005speed\030\006 \001(\002\022\020\n\010altitu" +
      "de\030\007 \001(\005\022\017\n\007locType\030\010 \001(\005\022\021\n\tgpsStatus\030\t" +
      " \001(\005\022\021\n\tdirection\030\n \001(\002\022\021\n\tsatellite\030\013 \001" +
      "(\005B%\n\034com.nwnu.blockchain.protobufH\001P\001\210\001" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_nwnu_blockchain_protobuf_gps_data_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_nwnu_blockchain_protobuf_gps_data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_nwnu_blockchain_protobuf_gps_data_descriptor,
        new java.lang.String[] { "Id", "TerminalId", "DataTime", "Lon", "Lat", "Speed", "Altitude", "LocType", "GpsStatus", "Direction", "Satellite", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
