// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello_world.proto

package com.nwnu.blockchain.protobuf;

public interface MistralRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.nwnu.blockchain.protobuf.MistralRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
