// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello_world.proto

package com.nwnu.blockchain.protobuf;

public interface MistralResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.nwnu.blockchain.protobuf.MistralResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
