// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello_world.proto

package com.nwnu.blockchain.protobuf;

public final class MistralProto {
  private MistralProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_nwnu_blockchain_protobuf_MistralRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_nwnu_blockchain_protobuf_MistralRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_nwnu_blockchain_protobuf_MistralResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_nwnu_blockchain_protobuf_MistralResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021hello_world.proto\022\034com.nwnu.blockchain" +
      ".protobuf\"\036\n\016MistralRequest\022\014\n\004name\030\001 \001(" +
      "\t\"\"\n\017MistralResponse\022\017\n\007message\030\001 \001(\t2y\n" +
      "\016MistralService\022g\n\010SayHello\022,.com.nwnu.b" +
      "lockchain.protobuf.MistralRequest\032-.com." +
      "nwnu.blockchain.protobuf.MistralResponse" +
      "B.\n\034com.nwnu.blockchain.protobufB\014Mistra" +
      "lProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_nwnu_blockchain_protobuf_MistralRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_nwnu_blockchain_protobuf_MistralRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_nwnu_blockchain_protobuf_MistralRequest_descriptor,
        new String[] { "Name", });
    internal_static_com_nwnu_blockchain_protobuf_MistralResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_nwnu_blockchain_protobuf_MistralResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_nwnu_blockchain_protobuf_MistralResponse_descriptor,
        new String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
